default:
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y make
    - make --version

stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - make build
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $DEPLOY_IMAGE == "true"

deploy_image:
  stage: deploy
  script:
    - make login
    - make push
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $DEPLOY_IMAGE == "true"
  dependencies:
    - build_image
