# default:
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind
#   before_script:
#     - docker info

#   before_script:
#     - apk update && apk add make
#     - make --version

variables:
#   DOCKER_HOST: tcp://docker:2375
#   DOCKER_TLS_CERTDIR: ""
   GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - make build
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $DEPLOY_IMAGE == "true"

deploy_image:
  stage: deploy
  script:
    - make login
    - make push
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $DEPLOY_IMAGE == "true"
  dependencies:
    - build_image
