default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

  before_script:
    - apk update && apk add make
    - make --version

variables:
  ########################
  # To effectively clone submodules repos
  # 1. Go to child repos under settings > ci/cd > token access
  # 2. Add the parent repo e.g amazing_ai/llm_apps
  ########################
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build

build_image:
  stage: build
  before_script:
    - make login
    
  script:
    - make build
    - make push
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $DEPLOY_IMAGE == "true"
