########################
# To effectively clone submodules repos
# 1. Go to child repos under settings > ci/cd > token access
# 2. Add the parent repo e.g amazing_ai/llm_apps
########################
default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

services:
  - docker:dind

before_script:
  - amazon-linux-extras install docker
  - yum -y install make 
  - aws --version
  - docker --version
  - make --version

 
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build

build_image:
  stage: build
  script:
    - make dh_login
    - make img_build
    - make img_pull
  
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $DEPLOY_IMAGE == "true"