FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY lingua_trainer/app /app/lingua_trainer/app
COPY streamlit_apps /app/streamlit_apps
COPY app.py app.py

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]