FROM python:3.9-slim

WORKDIR /app

COPY .env /app/.env
ENV ENVFILE /app/.env

COPY requirements_backend.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ /app/
COPY lingua_trainer/app/word_explorer.py /app/lingua_trainer/challenges/

EXPOSE 8100

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8100"]
