FROM python:3.9-slim

WORKDIR /app

COPY requirements_streamlit_apps.txt .

RUN pip install --no-cache-dir -r requirements_streamlit_apps.txt

COPY streamlit_apps/ /app/

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]