name: llm
channels:
  - conda-forge
  - defaults
dependencies:
  - langchain=0.0.190=pyhd8ed1ab_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pip:
      - openai==0.27.8
      - python-dotenv==1.0.0
      - google-search-results=2.4.2
